# 01. Importing Libraries

In [208]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd
import scipy.stats as st
from collections import Counter
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.preprocessing import MultiLabelBinarizer

# 02. Importing Data

In [115]:
books = pd.read_csv('../01. Data/books_combined.csv')

In [118]:
books.head()

,rank,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url
0,1.0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,"First published September 14, 2008","Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,"374 pages, Hardcover",The Hunger Games#1,NaN,NaN,NaN,NaN,NaN
1,2.0,Pride and Prejudice,Jane Austen,4.30,4920467.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,"First published January 28, 1813","Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...","279 pages, Paperback",NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,To Kill a Mockingbird,Harper Lee,4.26,7016855.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,"First published July 11, 1960","Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...","323 pages, Paperback",To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN
3,4.0,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,"First published June 21, 2003","Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,"896 pages, Hardcover",Harry Potter#5,NaN,NaN,NaN,NaN,NaN
4,5.0,The Book Thief,Markus Zusak,4.39,2935583.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,"First published September 1, 2005","Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,"592 pages, Kindle Edition",NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
books.shape

(2004, 18)

# 03. Cleaning the full dataframe

In [120]:
books['rank'].describe()

count    1004.000000
mean      508.044821
std       292.110079
min         1.000000
25%       255.750000
50%       508.500000
75%       760.250000
max      1013.000000
Name: rank, dtype: float64

In [121]:
books['rank'].isnull().sum()

np.int64(1000)

In [122]:
# making a book_id column and dropping rank
books = books.reset_index(drop=True)
books.index.name = 'book_id'

books = books.drop(columns=['rank'])

In [123]:
books.head()

,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url
book_id,,,,,,,,,,,,,,,,,
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,"First published September 14, 2008","Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,"374 pages, Hardcover",The Hunger Games#1,NaN,NaN,NaN,NaN,NaN
1,Pride and Prejudice,Jane Austen,4.30,4920467.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,"First published January 28, 1813","Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...","279 pages, Paperback",NaN,NaN,NaN,NaN,NaN,NaN
2,To Kill a Mockingbird,Harper Lee,4.26,7016855.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,"First published July 11, 1960","Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...","323 pages, Paperback",To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN
3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,"First published June 21, 2003","Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,"896 pages, Hardcover",Harry Potter#5,NaN,NaN,NaN,NaN,NaN
4,The Book Thief,Markus Zusak,4.39,2935583.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,"First published September 1, 2005","Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,"592 pages, Kindle Edition",NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
books.dtypes

title                 str
author                str
avg_rating        float64
num_ratings       float64
cover_img_url         str
goodreads_url         str
source                str
year_published        str
genres                str
description           str
pages                 str
series                str
isbn                  str
publisher             str
language              str
ol_key                str
google_url            str
dtype: object

In [125]:
# converting num_rating into int
books['num_ratings'] = books['num_ratings'].astype('Int64')

In [126]:
books.dtypes

title                 str
author                str
avg_rating        float64
num_ratings         Int64
cover_img_url         str
goodreads_url         str
source                str
year_published        str
genres                str
description           str
pages                 str
series                str
isbn                  str
publisher             str
language              str
ol_key                str
google_url            str
dtype: object

In [127]:
# checking for patterns in year_published column
books['year_published'].unique()

<ArrowStringArray>
['First published September 14, 2008',   'First published January 28, 1813',
      'First published July 11, 1960',      'First published June 21, 2003',
  'First published September 1, 2005',    'First published October 5, 2005',
    'First published August 17, 1945',    'First published January 1, 1954',
    'First published January 1, 1956',   'First published January 10, 2012',
 ...
                             '1200.0',                             '1788.0',
                             '1817.0',                             '1916.0',
                             '1874.0',                             '1835.0',
                             '1933.0',                             '1896.0',
                             '1934.0',                             '1829.0']
Length: 1054, dtype: str

In [128]:
# cleaning the year_published column
books['year_published'] = books['year_published'].str.extract(r'(\d{4})')

In [129]:
books['year_published'].unique()

<ArrowStringArray>
['2008', '1813', '1960', '2003', '2005', '1945', '1954', '1956', '2012',
 '1890',
 ...
 '1743', '1786', '1867', '1467', '1200', '1788', '1835', '1933', '1896',
 '1829']
Length: 245, dtype: str

In [130]:
books['year_published'].dtype

In [131]:
# changing it to number and checking it
books['year_published'] = pd.to_numeric(books['year_published'], errors='coerce').astype('Int64')
books['year_published'].dtype

Int64Dtype()

In [132]:
# checking for patterns in pages column
books['pages'].unique()

<ArrowStringArray>
[             '374 pages, Hardcover',              '279 pages, Paperback',
              '323 pages, Paperback',              '896 pages, Hardcover',
         '592 pages, Kindle Edition',              '498 pages, Paperback',
  '141 pages, Mass Market Paperback', '1728 pages, Mass Market Paperback',
              '767 pages, Paperback',              '313 pages, Hardcover',
 ...
                             '684.0',                             '736.0',
                             '770.0',                             '380.0',
                             '590.0',                             '884.0',
                             '958.0',                             '874.0',
                             '749.0',                            '1856.0']
Length: 1189, dtype: str

In [133]:
# cleaning the pages column
books['pages'] = books['pages'].str.extract(r'(\d+)')

In [134]:
books['pages'].unique()

<ArrowStringArray>
[ '374',  '279',  '323',  '896',  '592',  '498',  '141', '1728',  '767',
  '313',
 ...
  '177',  '902', '1232',  '575',  '770',  '884',  '958',  '874',  '749',
 '1856']
Length: 669, dtype: str

In [135]:
books['pages'].dtype

In [136]:
# changing it to number and checking it
books['pages'] = pd.to_numeric(books['pages'], errors='coerce').astype('Int64')
books['pages'].dtype

Int64Dtype()

Manual imputation for some important data

In [138]:
# checking columns that will need manual imputation 
books.isnull().sum()

title                0
author               1
avg_rating         755
num_ratings        733
cover_img_url        4
goodreads_url     1000
source               0
year_published      20
genres               7
description          0
pages               24
series            1529
isbn              1008
publisher         1009
language          1004
ol_key            1004
google_url        1017
dtype: int64

In [139]:
# checking the rows with null to be able to search and manually fill them
books[books['year_published'].isnull()]

,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url
book_id,,,,,,,,,,,,,,,,,
48,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,4.62,4177757,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/136251.Har...,GoodReads,<NA>,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
50,The Odyssey,Homer,3.84,1224393,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1381.The_O...,GoodReads,<NA>,"Classics, Fiction, Poetry, Mythology, Fantasy,...","Sing to me of the man, Muse, the man of twists...",541,NaN,NaN,NaN,NaN,NaN,NaN
72,The Adventures of Sherlock Holmes (Sherlock Ho...,Arthur Conan Doyle,4.30,330762,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/3590.The_A...,GoodReads,<NA>,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
90,Gone Girl,Gillian Flynn,4.15,3508073,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19288043-g...,GoodReads,<NA>,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
152,"The Last Thing He Told Me (Hannah Hall, #1)",Laura Dave,3.83,1187142,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/54981009-t...,GoodReads,<NA>,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
275,Beloved,Toni Morrison,3.99,503338,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/6149.Beloved,GoodReads,<NA>,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
291,The Iliad / The Odyssey,Homer,4.07,85200,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1375.The_I...,GoodReads,<NA>,"Classics, Fiction, Poetry, Mythology, Fantasy,...",Gripping listeners and readers for more than 2...,1556,NaN,NaN,NaN,NaN,NaN,NaN
470,Tao Te Ching,Lao Tzu,4.29,185834,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/67896.Tao_...,GoodReads,<NA>,"Philosophy, Nonfiction, Classics, Spirituality...",A lucid translation of the well-known Taoist c...,107,SUNY series in Chinese Philosophy and Culture,NaN,NaN,NaN,NaN,NaN
476,القرآن الكريم,الله,4.38,73505,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/646462._,GoodReads,<NA>,"Religion, Islam, Nonfiction, Classics, Philoso...",The Quran (English pronunciation: /kɔrˈɑːn/; A...,604,NaN,NaN,NaN,NaN,NaN,NaN
518,Hidden Pictures,Jason Rekulak,4.14,646390,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58724923-h...,GoodReads,<NA>,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
563,Shantaram,Gregory David Roberts,4.28,244510,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/33600.Shan...,GoodReads,<NA>,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
585,The Republic,Plato,3.97,229951,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/30289.The_...,GoodReads,<NA>,"Philosophy, Classics, Nonfiction, Politics, Hi...",Presented in the form of a dialogue between So...,416,Plato's Dialogues#4,NaN,NaN,NaN,NaN,NaN
685,The Art of War,Sun Tzu,3.94,586039,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/10534.The_...,GoodReads,<NA>,"Classics, Nonfiction, Philosophy, History, War...","Twenty-Five Hundred years ago, Sun Tzu wrote t...",170,NaN,NaN,NaN,NaN,NaN,NaN
727,The Arabian Nights,Anonymous,4.02,82599,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/93101.The_...,GoodReads,<NA>,"Classics, Fiction, Fantasy, Short Stories, Lit...",This volume reproduces the 1932 Modern Library...,1049,The Arabian Nights,NaN,NaN,NaN,NaN,NaN
768,The Iliad,Homer,3.93,522857,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1371.The_I...,GoodReads,<NA>,"Classics, Poetry, Fiction, Mythology, Literatu...","Dating to the ninth century B.C., Homer’s time...",614,NaN,NaN,NaN,NaN,NaN,NaN
795,"Oedipus Rex (The Theban Plays, #1)",Sophocles,3.73,241215,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1554.Oedip...,GoodReads,<NA>,"Classics, Plays, Fiction, Drama, School, Mytho...","""...what man wins more happiness than just its...",75,The Theban Plays#1,NaN,NaN,NaN,NaN,NaN
866,Meditations,Marcus Aurelius,4.28,367342,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/30659.Medi...,GoodReads,<NA>,"Philosophy, Nonfiction, Classics, History, Sel...",Written in Greek by the only Roman emperor who...,254,NaN,NaN,NaN,NaN,NaN,NaN
880,The Aeneid,Virgil,3.88,146311,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/12914.The_...,GoodReads,<NA>,"Classics, Poetry, Fiction, Mythology, Literatu...","The Aeneid – thrilling, terrifying and poignan...",442,NaN,NaN,NaN,NaN,NaN,NaN
928,"Antigone (Theban Plays, #3)",Sophocles,3.69,181018,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/7728.Antigone,GoodReads,<NA>,"Classics, Plays, School, Fiction, Drama, Mytho...",The curse placed on Oedipus lingers and haunts...,80,The Theban Plays#3,NaN,NaN,NaN,NaN,NaN
1710,The Invisible Man,H. G. Wells,4.00,14,https://covers.openlibrary.org/b/id/6419199-L.jpg,NaN,Open Library,<NA>,"Ciencia-ficción, Classic Literature, Fiction, ...","This book is the story of Griffin, a scientist...",170,NaN,1400150663,George Newnes Ltd.,"cat, fre, por, eng, chi, spa, ger, rus, mon, ita",/works/OL52266W,https://play.google.com/store/books/details?id...

In [140]:
# changing year_published to object to be able to fill the null values with the BC values
books['year_published'] = books['year_published'].astype('object')

In [ ]:
# substituteing the null values with the year of the first edition of the book
# AC
books.loc[48, 'year_published'] = 2007 
books.loc[72, 'year_published'] = 1892 
books.loc[90, 'year_published'] = 2012   
books.loc[152, 'year_published'] = 2021  
books.loc[275, 'year_published'] = 1987  
books.loc[518, 'year_published'] = 2022  
books.loc[563, 'year_published'] = 2003  
books.loc[476, 'year_published'] = 632   
books.loc[866, 'year_published'] = 180   
books.loc[1710, 'year_published'] = 1897

# BC
books.loc[50, 'year_published'] = '800 BC'    
books.loc[291, 'year_published'] = '800 BC'   
books.loc[470, 'year_published'] = '400 BC'   
books.loc[585, 'year_published'] = '375 BC'   
books.loc[685, 'year_published'] = '500 BC'   
books.loc[727, 'year_published'] = '800 BC'  
books.loc[768, 'year_published'] = '800 BC'   
books.loc[795, 'year_published'] = '429 BC'   
books.loc[880, 'year_published'] = '19 BC'    
books.loc[928, 'year_published'] = '441 BC'

In [142]:
# checking rows with null values in genres column
books[books['genres'].isnull()]

,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url
book_id,,,,,,,,,,,,,,,,,
48,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,4.62,4177757,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/136251.Har...,GoodReads,2007,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
72,The Adventures of Sherlock Holmes (Sherlock Ho...,Arthur Conan Doyle,4.30,330762,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/3590.The_A...,GoodReads,1892,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
90,Gone Girl,Gillian Flynn,4.15,3508073,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19288043-g...,GoodReads,2012,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
152,"The Last Thing He Told Me (Hannah Hall, #1)",Laura Dave,3.83,1187142,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/54981009-t...,GoodReads,2021,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
275,Beloved,Toni Morrison,3.99,503338,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/6149.Beloved,GoodReads,1987,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
518,Hidden Pictures,Jason Rekulak,4.14,646390,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58724923-h...,GoodReads,2022,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
563,Shantaram,Gregory David Roberts,4.28,244510,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/33600.Shan...,GoodReads,2003,NaN,page unavailableAn unexpected error occurred. ...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
pd.set_option('display.max_colwidth', None)

In [146]:
# checking some collections genres to generate the same input for the null values of same collection
# HP books
books[books['title'].str.contains('Harry Potter', case=False)][['title', 'genres']]

,title,genres
book_id,,
3,"Harry Potter and the Order of the Phoenix (Harry Potter, #5)","Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens"
48,"Harry Potter and the Deathly Hallows (Harry Potter, #7)",NaN
56,"Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)","Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens"
69,"Harry Potter and the Philosopher's Stone (Harry Potter, #1)","Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens"
89,"Harry Potter and the Goblet of Fire (Harry Potter, #4)","Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens"
104,"Harry Potter and the Half-Blood Prince (Harry Potter, #6)","Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens"
109,"Harry Potter and the Sorcerer's Stone (Harry Potter, #1)","Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens"
117,"Harry Potter and the Chamber of Secrets (Harry Potter, #2)","Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens"
439,"Harry Potter Series Box Set (Harry Potter, #1-7)","Fantasy, Young Adult, Fiction, Harry Potter, Magic, Childrens, Adventure"
1434,Harry Potter and the Cursed Child,"Drama, Fantasy, Magic, Juvenile Drama, Good and evil"

In [147]:
# Sherlock Holmes books
books[books['title'].str.contains('Sherlock Holmes', case=False)][['title', 'genres']]

,title,genres
book_id,,
72,"The Adventures of Sherlock Holmes (Sherlock Holmes, #3)",NaN
350,The Complete Sherlock Holmes,"Classics, Mystery, Fiction, Crime, Short Stories, Audiobook, Detective"
413,"The Hound of the Baskervilles (Sherlock Holmes, #5)","Classics, Mystery, Fiction, Crime, Detective, Mystery Thriller, Thriller"
1835,The Devil and Sherlock Holmes,"Literary Criticism, Nonfiction, True crime stories, Case studies, murder"

In [148]:
# Hannah Hall books
books[books['title'].str.contains('Hannah Hall', case=False)][['title', 'genres']]

                                               title genres
book_id
152      The Last Thing He Told Me (Hannah Hall, #1)    NaN

In [149]:
# imputting genres manually based on the title and author of the book
books.loc[48, 'genres'] = 'Fantasy, Fiction, Young Adult, Harry Potter, Magic, Audiobook, Childrens'
books.loc[72, 'genres'] = 'Classics, Mystery, Fiction, Crime, Short Stories, Audiobook, Detective'
books.loc[90, 'genres'] = 'Mystery, Thriller, Fiction, Suspense'
books.loc[152, 'genres'] = 'Mystery, Thriller, Fiction, Suspense'
books.loc[275, 'genres'] = 'Fiction, Historical Fiction, Classics, Literary'
books.loc[518, 'genres'] = 'Horror, Mystery, Fiction, Thriller'
books.loc[563, 'genres'] = 'Biography, Adventure, Historical Fiction, Travel'

In [150]:
# checking how many rows have description "page unavailable"
books['description'].str.contains('page unavailable').sum()

np.int64(7)

In [151]:
# checking which rows for manual imputation of description
books[books['description'].str.contains('page unavailable', case=False)][['title', 'author', 'description', 'source']]

,title,author,description,source
book_id,,,,
48,"Harry Potter and the Deathly Hallows (Harry Potter, #7)",J.K. Rowling,page unavailableAn unexpected error occurred. We will investigate this problem as soon as possible — please check back soon!,GoodReads
72,"The Adventures of Sherlock Holmes (Sherlock Holmes, #3)",Arthur Conan Doyle,page unavailableAn unexpected error occurred. We will investigate this problem as soon as possible — please check back soon!,GoodReads
90,Gone Girl,Gillian Flynn,page unavailableAn unexpected error occurred. We will investigate this problem as soon as possible — please check back soon!,GoodReads
152,"The Last Thing He Told Me (Hannah Hall, #1)",Laura Dave,page unavailableAn unexpected error occurred. We will investigate this problem as soon as possible — please check back soon!,GoodReads
275,Beloved,Toni Morrison,page unavailableAn unexpected error occurred. We will investigate this problem as soon as possible — please check back soon!,GoodReads
518,Hidden Pictures,Jason Rekulak,page unavailableAn unexpected error occurred. We will investigate this problem as soon as possible — please check back soon!,GoodReads
563,Shantaram,Gregory David Roberts,page unavailableAn unexpected error occurred. We will investigate this problem as soon as possible — please check back soon!,GoodReads

In [152]:
# manual imputations according to source
books.loc[48, 'description'] = "It's no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run. Professor Dumbledore has given them clues about what they need to do to defeat the dark wizard, Lord Voldemort, once and for all, but it's up to them to figure out what these hints and suggestions really mean. Their cross-country odyssey has them searching desperately for the answers, while evading capture or death at every turn. At the same time, their friendship, fortitude, and sense of right and wrong are tested in ways they never could have imagined. The ultimate battle between good and evil that closes out this final chapter of the epic series takes place where Harry's Wizarding life began: at Hogwarts. The satisfying conclusion offers shocking last-minute twists, incredible acts of courage, powerful new forms of magic, and the resolution of many mysteries. Above all, this intense, cathartic book serves as a clear statement of the message at the heart of the Harry Potter series: that choice matters much more than destiny, and that love will always triumph over death."
books.loc[72, 'description'] = 'The world-famous crime-solving duo Holmes and Watson are on sterling form in this excellent compilation of six unabridged adventures. Included in the third volume of the audio collection read by famed actor Edward Hardwicke are: "A Scandal in Bohemia," which inspired the Guy Richie-directed Sherlock Holmes film starring Robert Downey Junior; "Silver Blaze," in which a racehorse disappears on the eve of an important meet and its trainer appears to have been murdered; "The Adventure of the Copper Beeches," in which a young woman agrees to a governess post with an impressive salary but strange conditions; as well as "The Adventure of the Priory School," "The Red-Headed League," and "The Adventure of the Blue Carbuncle."'
books.loc[90, 'description'] = "Who are you? What have we done to each other? These are the questions Nick Dunne finds himself asking on the morning of his fifth wedding anniversary when his wife Amy suddenly disappears. The police suspect Nick. Amy's friends reveal that she was afraid of him, that she kept secrets from him. He swears it isn't true. A police examination of his computer shows strange searches. He says they weren't made by him. And then there are the persistent calls on his mobile phone. So what did happen to Nick's beautiful wife?"
books.loc[152, 'description'] = "Before Owen Michaels disappears, he smuggles a note to his beloved wife of one year: Protect her. Despite her confusion and fear, Hannah Hall knows exactly to whom the note refers—Owen’s sixteen-year-old daughter, Bailey. Bailey, who lost her mother tragically as a child. Bailey, who wants absolutely nothing to do with her new stepmother. As Hannah’s increasingly desperate calls to Owen go unanswered, as the FBI arrests Owen’s boss, as a US marshal and federal agents arrive at her Sausalito home unannounced, Hannah quickly realizes her husband isn’t who he said he was. And that Bailey just may hold the key to figuring out Owen’s true identity—and why he really disappeared. Hannah and Bailey set out to discover the truth. But as they start putting together the pieces of Owen’s past, they soon realize they’re also building a new future—one neither of them could have anticipated."
books.loc[275, 'description'] = "Staring unflinchingly into the abyss of slavery, this spellbinding novel transforms history into a story as powerful as Exodus and as intimate as a lullaby. Sethe, its protagonist, was born a slave and escaped to Ohio, but eighteen years later she is still not free. She has too many memories of Sweet Home, the beautiful farm where so many hideous things happened. And Sethe's new home is haunted by the ghost of her baby, who died nameless and whose tombstone is engraved with a single word: Beloved. Filled with bitter poetry and suspense as taut as a rope, Beloved is a towering achievement by Nobel Prize laureate Toni Morrison."
books.loc[518, 'description'] = "From Jason Rekulak, Edgar-nominated author of The Impossible Fortress, comes a wildly inventive spin on the classic horror story in Hidden Pictures, a supernatural thriller about a woman working as a nanny for a young boy with strange and disturbing secrets. Fresh out of rehab, Mallory Quinn takes a job as a babysitter for Ted and Caroline Maxwell. She is to look after their five-year-old son, Teddy. Mallory immediately loves it. She has her own living space, goes out for nightly runs, and has the stability she craves. And she sincerely bonds with Teddy, a sweet, shy boy who is never without his sketchbook and pencil. His drawings are the usual fare: trees, rabbits, balloons. But one day, he draws something different: a man in a forest, dragging a woman’s lifeless body. Then, Teddy’s artwork becomes increasingly sinister, and his stick figures quickly evolve into lifelike sketches well beyond the ability of any five-year-old. Mallory begins to wonder if these are glimpses of a long-unsolved murder, perhaps relayed by a supernatural force. Knowing just how crazy it all sounds, Mallory nevertheless sets out to decipher the images and save Teddy before it’s too late."
books.loc[563, 'description'] = """It took me a long time and most of the world to learn what I know about love and fate and the choices we make, but the heart of it came to me in an instant, while I was chained to a wall and being tortured. So begins this epic, mesmerizing first novel set in the underworld of contemporary Bombay. Shantaram is narrated by Lin, an escaped convict with a false passport who flees maximum security prison in Australia for the teeming streets of a city where he can disappear. Accompanied by his guide and faithful friend, Prabaker, the two enter Bombay's hidden society of beggars and gangsters, prostitutes and holy men, soldiers and actors, and Indians and exiles from other countries, who seek in this remarkable place what they cannot find elsewhere. As a hunted man without a home, family, or identity, Lin searches for love and meaning while running a clinic in one of the city's poorest slums, and serving his apprenticeship in the dark arts of the Bombay mafia. Based on the life of the author, it is by any measure the debut of an extraordinary voice in literature."""

In [153]:
books[books['author'].isnull()]

,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url
book_id,,,,,,,,,,,,,,,,,
1240,The business world,NaN,NaN,<NA>,NaN,NaN,Open Library,1912,"Great Britain -- Commerce -- History., Great Britain -- Industries -- History.","Accounts of W.V. Bowater and Sons; George Briggs and Co., alderman and sheriff; C.A. Hanson, C.C. Wakefield and Co.",336,NaN,9781501500725,Dod's Publications,eng,/works/OL19729600M,https://play.google.com/store/books/details?id=NvBeCAAAQBAJ&source=gbs_api

In [154]:
# manual inputation of author name (first one)
books.loc[1240, 'author'] = 'Dwi Noverini Djenar'

In [155]:
books.isnull().sum()

title                0
author               0
avg_rating         755
num_ratings        733
cover_img_url        4
goodreads_url     1000
source               0
year_published       0
genres               0
description          0
pages               24
series            1529
isbn              1008
publisher         1009
language          1004
ol_key            1004
google_url        1017
dtype: int64

In [156]:
pd.reset_option('display.max_colwidth')

In [ ]:
# exporting the cleaned dataframe as is
# books.to_csv('../01. Data/books_cleaned.csv', index=True)

# 04. Transformations for ML

In [212]:
# creating a copy of the dataframe to work with
books_model = books.copy()

In [185]:
# dropping columns that wont be used for the ML model (year not used due to object values for BC dates)
columns_to_drop_clustering = ['cover_img_url', 'goodreads_url', 'source', 'series', 'isbn', 'publisher', 'language', 'ol_key', 'google_url', 'year_published']

books_model = books_model.drop(columns=columns_to_drop_clustering)

In [186]:
books_model.head()

,title,author,avg_rating,num_ratings,genres,description,pages
book_id,,,,,,,
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374
1,Pride and Prejudice,Jane Austen,4.30,4920467,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279
2,To Kill a Mockingbird,Harper Lee,4.26,7016855,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323
3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896
4,The Book Thief,Markus Zusak,4.39,2935583,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592

In [187]:
books_model['author'].nunique()

1377

In [188]:
# dropping title and author as those are identifiers. Author dropped because there are to many unique values and it would be hard to encode them
books_model = books_model.drop(columns=['title', 'author'])

In [189]:
books_model.head()

,avg_rating,num_ratings,genres,description,pages
book_id,,,,,
0,4.35,10115839,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374
1,4.30,4920467,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279
2,4.26,7016855,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323
3,4.50,3868435,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896
4,4.39,2935583,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592

In [190]:
books_model.isnull().sum()

avg_rating     755
num_ratings    733
genres           0
description      0
pages           24
dtype: int64

In [191]:
# filling null in avg_rating and num_ratings with median of each column
books_model['avg_rating'] = books_model['avg_rating'].fillna(books_model['avg_rating'].median())
books_model['num_ratings'] = books_model['num_ratings'].fillna(books_model['num_ratings'].median())
books_model['pages'] = books_model['pages'].fillna(round(books_model['pages'].median()))

In [192]:
books_model.isnull().sum()

avg_rating     0
num_ratings    0
genres         0
description    0
pages          0
dtype: int64

Running TF-IDF and PCA in description column

In [193]:
# running the TF-IDF vectorizer on description column
tfidf = TfidfVectorizer(max_features=5000)
X_description = tfidf.fit_transform(books_model['description']).toarray()
print('TF-IDF shape:', X_description.shape)

TF-IDF shape: (2004, 5000)

In [194]:
# running PCA to reduce the dimensionality of the TF-IDF created matrix
pca = PCA(n_components=50)
X_description_pca = pca.fit_transform(X_description)
print('PCA shape:', X_description_pca.shape)

PCA shape: (2004, 50)

OHE on genre column

In [209]:
# creating new column with the list of genres for each book
def split_genres(genres_string):
    if pd.isna(genres_string):
        return []
    genres = re.split(r'[,;|]', genres_string)
    cleaned = []
    for genre in genres:
        cleaned.append(genre.strip())
    return cleaned

books_model['genres_list'] = books_model['genres'].apply(split_genres)

In [210]:
# cleaning and standardizing the genres column_list
def clean_genres(genre_list):
    cleaned = []
    for genre in genre_list:
        cleaned.append(genre.strip().title())
    return cleaned

books_model['genres_list'] = books_model['genres_list'].apply(clean_genres)

In [211]:
print(genre_counts.most_common())

[('Fiction', 1160), ('Classics', 443), ('Fantasy', 423), ('Young Adult', 302), ('Romance', 291), ('Audiobook', 253), ('Historical Fiction', 232), ('Book Club', 199), ('Literature', 196), ('Mystery', 196), ('Contemporary', 181), ('Thriller', 165), ('Nonfiction', 161), ('Science Fiction', 151), ('Novels', 136), ('History', 128), ('Adventure', 121), ('Biography', 119), ('Historical', 112), ('Philosophy', 110), ('Childrens', 102), ('Mystery Thriller', 97), ('Crime', 97), ('Horror', 89), ('Paranormal', 81), ('Adult', 71), ('Magic', 70), ('Dystopia', 69), ('Middle Grade', 67), ('Suspense', 65), ('Literary Fiction', 64), ('Drama', 63), ('School', 60), ('general', 58), ('fiction', 54), ('Humor', 52), ('Vampires', 49), ('Poetry', 49), ('Psychology', 49), ('Science Fiction Fantasy', 46), ('Urban Fantasy', 46), ('True Crime', 46), ('science fiction', 46), ('Murder', 41), ('Travel', 40), ('Science fiction', 40), ('Description and travel', 37), ('Religion', 36), ('Business', 35), ('High Fantasy', 34), ('Mythology', 34), ('American', 33), ('Cooking', 33), ('Case studies', 31), ('Realistic Fiction', 29), ('Economics', 29), ('Animals', 28), ('Magical Realism', 28), ('Memoir', 28), ('War', 27), ('Paranormal Romance', 27), ('Plays', 27), ('Short Stories', 26), ('Epic Fantasy', 25), ('LGBT', 24), ('Chick Lit', 24), ('Romantasy', 24), ('Politics and government', 23), ('Cookery', 23), ('Gothic', 22), ('Classic Literature', 22), ('Contemporary Romance', 22), ('biography', 22), ('Time Travel', 20), ('Science', 20), ('Juvenile fiction', 20), ('Gardening', 20), ('Coming Of Age', 19), ('Queer', 19), ('Education', 19), ('New York Times bestseller', 19), ('Picture Books', 18), ('France', 18), ('Supernatural', 18), ('American Science fiction', 18), ('Political science', 18), ('Success', 18), ('Christian', 17), ('Mental Health', 17), ('Comedy', 17), ('Fae', 17), ('Sociology', 17), ('Psychological aspects', 17), ('history', 17), ('Adult Fiction', 16), ('Spirituality', 16), ('Juvenile literature', 16), ('Politics', 15), ('Textbooks', 15), ('Conduct of life', 15), ('Self Help', 14), ('19th Century', 14), ('India', 14), ('New Adult', 14), ('Dark', 14), ('United states', 14), ('Journeys', 14), ('Art', 13), ('Criminals', 13), ('Histoire', 13), ('description and travel', 13), ("Children's poetry", 13), ('Japan', 12), ('Shakespeare', 12), ('Feminism', 12), ('Africa', 12), ('Young Adult Fantasy', 12), ('Christianity', 12), ('Civilization', 12), ('Self-help techniques', 12), ('Post Apocalyptic', 11), ('Teen', 11), ('Enemies To Lovers', 11), ('Biography & Autobiography', 11), ('Open Library Staff Picks', 11), ('Organized crime', 11), ('Self-actualization (Psychology)', 11), ('Interpersonal relations', 11), ('Self-help', 11), ('American poetry', 11), ('Harry Potter', 10), ('Percy Jackson', 10), ('Russia', 10), ('Theatre', 10), ('British Literature', 10), ('Love', 10), ('Dark Romance', 10), ('philosophy', 10), ('Social life and customs', 10), ('Biographies', 10), ('Crimes against', 10), ('Voyages and travels', 10), ('mystery & detective', 10), ('Early works to 1800', 10), ('personal development', 10), ('Russian Literature', 9), ('Read For School', 9), ('Autobiography', 9), ('Dragons', 9), ('Inspirational', 9), ('Holocaust', 9), ('Serial murders', 9), ('thrillers', 9), ('Economic conditions', 9), ('Time travel', 9), ('hard science fiction', 9), ('Life on other planets', 9), ('American Cookery', 9), ('Dark Academia', 8), ('Italy', 8), ('Noir', 8), ('Erotica', 8), ('Banned Books', 8), ('Space', 8), ('Finance', 8), ('American literature', 8), ('Large type books', 8), ('Women', 8), ('Serial murderers', 8), ("Children's fiction", 8), ('Gardens', 8), ('New York Times reviewed', 8), ('Self-actualization (psychology)', 8), ('true crime', 8), ('Cooking & Food', 8), ('Ebooks', 7), ('Angels', 7), ('Victorian', 7), ('German Literature', 7), ('Japanese Literature', 7), ('20th Century', 7), ('Retellings', 7), ('World War II', 7), ('Nature', 7), ('Fantasy Romance', 7), ('Friendship', 7), ('united states', 7), ('Philosophie', 7), ('juvenile literature', 7), ('Murderers', 7), ('Young adult fiction', 7), ('crime', 7), ('Investigation', 7), ('Fiction in English', 7), ('Kidnapping', 7), ('politics and government', 7), ('Long Now Manual for Civilization', 7), ('New Thought', 7), ('Social aspects', 7), ('Management', 7), ('Liberty', 7), ('Poetry (poetic works by one author)', 7), ('French Cookery', 7), ('Biography Memoir', 6), ('French Literature', 6), ('Graphic Novels', 6), ('Westerns', 6), ('BDSM', 6), ('Family', 6), ('Physics', 6), ('Jane Austen', 6), ('Personal Development', 6), ('Presidents', 6), ('Leadership', 6), ('Communication', 6), ('Nutrition', 6), ('American Authors', 6), ('Trials (Murder)', 6), ('Mental health', 6), ('Religion & Spirituality', 6), ('action & adventure', 6), ('Detective and mystery stories', 6), ('Children', 6), ('suspense', 6), ('Modern History', 6), ('World politics', 6), ('Motivation (Psychology)', 6), ('Self-Improvement', 6), ('psychology', 6), ('Self-realization', 6), ('romance', 6), ('Vegetable gardening', 6), ('Economic policy', 6), ('Economic development', 6), ('American Cooking', 6), ('French Cooking', 6), ('french', 6), ('Space Opera', 5), ('Detective', 5), ('Historical Romance', 5), ('Spanish Literature', 5), ('Ireland', 5), ('Food', 5), ('Comics', 5), ('African American', 5), ('China', 5), ('Music', 5), ('Fairy Tales', 5), ('Race', 5), ('Greek Mythology', 5), ('Satire', 5), ('Colleen Hoover', 5), ('Abuse', 5), ('Reference', 5), ('Sports', 5), ('Psychotherapy', 5), ('Cooks', 5), ('Young women', 5), ('English Authors', 5), ('Childhood and youth', 5), ('Correspondence', 5), ('Spanish language materials', 5), ('Mafia', 5), ('Sex crimes', 5), ('Wizards', 5), ('Economic aspects', 5), ('fantasy', 5), ('open_syllabus_project', 5), ('Gardeners', 5), ('Historia', 5), ('Science Fiction & Fantasy', 5), ('World history', 5), ('Translations into English', 5), ('Self-Help', 5), ('Psychological aspects of Success', 5), ('Miscellanea', 5), ('Man-woman relationships', 5), ('Fantasy fiction', 5), ('English', 5), ('Filosofía', 5), ('English drama', 5), ('Human-alien encounters', 5), ('Psychohistory', 5), ('Dune (Imaginary place)', 5), ('Business enterprises', 5), ('Industrial management', 5), ('Cookbooks', 5), ('Agatha Christie', 4), ('Steampunk', 4), ('Christmas', 4), ('Dogs', 4), ('Christian Fiction', 4), ('Cyberpunk', 4), ('Witches', 4), ('Aliens', 4), ('Asia', 4), ('Action', 4), ('Outlander', 4), ('Essays', 4), ('Collections', 4), ('Military Fiction', 4), ('Cats', 4), ('Health', 4), ('Scientists', 4), ('Biografía', 4), ('nonfiction', 4), ('Authors', 4), ('African Americans', 4), ('Rock musicians', 4), ('Anecdotes', 4), ('Missionaries', 4), ('Princesses', 4), ('Communism', 4), ('Religions', 4), ('Gay men', 4), ('Social conditions', 4), ('Children: Grades 1-2', 4), ('Police', 4), ('psychological', 4), ('murder', 4), ("Children's stories", 4), ('Money', 4), ('Capitalism', 4), ('Geschichte', 4), ('Socialism', 4), ('Fairy tales', 4), ('Criticism and interpretation', 4), ('psychological aspects', 4), ('Educational psychology', 4), ('Applied Psychology', 4), ('Change (Psychology)', 4), ('business', 4), ('Technology', 4), ('Body language', 4), ('Success in business', 4), ('Cosmology', 4), ('Married people', 4), ('Problems', 4), ('exercises', 4), ('Law', 4), ('Ethics', 4), ('Existentialism', 4), ('Humorous poetry', 4), ('Ancient Philosophy', 4), ('Robots', 4), ('Interplanetary voyages', 4), ('Hugo Award Winner', 4), ('English poetry', 4), ('american', 4), ('california', 4), ('United States', 4), ('Entrepreneurship', 4), ('Mass murder', 4), ('Économie politique', 4), ('Decision making', 4), ('Health & Fitness', 4), ('French', 4), ('Medieval', 3), ('Buddhism', 3), ('Books About Books', 3), ('High School', 3), ('Graphic Novels Comics', 3), ('Environment', 3), ('Kids', 3), ('Mental Illness', 3), ('Scotland', 3), ('Irish Literature', 3), ('Drugs', 3), ('Theology', 3), ('Faith', 3), ('Horses', 3), ('Germany', 3), ('Canada', 3), ('Indian Literature', 3), ('Jewish', 3), ('Fake Dating', 3), ('Speculative Fiction', 3), ('Espionage', 3), ('American History', 3), ('Spicy', 3), ('Greece', 3), ('Comics & graphic novels', 3), ('Neurosurgeons', 3), ('Businesspeople', 3), ('African American families', 3), ('Mathématiciens', 3), ('Singers', 3), ('Philosophers', 3), ('English literature', 3), ('PSYCHOLOGY', 3), ('satire', 3), ('Mentally ill', 3), ('Wealth', 3), ('Lesbians', 3), ('20th century', 3), ('American Poets', 3), ('Death', 3), ('Psychiatry and religion', 3), ('Families', 3), ('English Science fiction', 3), ('England', 3), ('family', 3), ('Mistaken identity', 3), ('Crime and criminals', 3), ('Jews', 3), ('Educational sociology', 3), ('Computer crimes', 3), ('Maps', 3), ('Criminal psychology', 3), ('Conspiracies', 3), ('Control (Psychology)', 3), ('Adventure stories', 3), ('Éducation', 3), ('Kunst', 3), ('World War', 3), ('Twenty-first century', 3), ('Europe', 3), ('greek', 3), ('Classical Mythology', 3), ('Natural history', 3), ('historical', 3), ('Historiography', 3), ('Ancient History', 3), ('Modern', 3), ('Economic history', 3), ('essays', 3), ('lectures', 3), ('Controversial literature', 3), ('Utopias', 3), ('Political culture', 3), ('Habit', 3), ('Catholic Church', 3), ('Change (psychology)', 3), ('Self-perception', 3), ('Game theory', 3), ('Personality', 3), ('Interpersonal communication', 3), ('Individualism', 3), ('Nonverbal communication', 3), ('New Age', 3), ('Einführung', 3), ('Work', 3), ('Happiness', 3), ('Ability', 3), ('Dictatorship', 3), ('Diaries', 3), ('Soldiers', 3), ('Mind and body', 3), ('self-love', 3), ('horror', 3), ('Travel writing', 3), ('Good and evil', 3), ('British and irish drama (dramatic works by one author)', 3), ('Twins', 3), ('Space and time', 3), ('Handbooks', 3), ('manuals', 3), ('literary fiction', 3), ('1914-1918', 3), ('Social sciences', 3), ('Political aspects', 3), ('Revolutions', 3), ('Constitutional law', 3), ('Drama (dramatic works by one author)', 3), ('German Philosophy', 3), ('Methodology', 3), ('Dune (imaginary place)', 3), ('Space colonies', 3), ('Space warfare', 3), ('award:hugo_award=novel', 3), ('True Crime / Espionage', 3), ('TRUE CRIME / Murder / General', 3), ('Homicide investigation', 3), ('Business communication', 3), ('New business enterprises', 3), ('Small business', 3), ('Microeconomics', 3), ('Business & Management', 3), ('Commerce', 3), ('Strategic planning', 3), ('economic conditions', 3), ('Health promotion', 3), ('International cooking', 3), ('Women cooks', 3), ('Australia', 2), ('Arthurian', 2), ('New York', 2), ('Southern Gothic', 2), ('Epic', 2), ('Southern', 2), ('Legal Thriller', 2), ('South Africa', 2), ('Civil War', 2), ('Islam', 2), ('Royalty', 2), ('Political Science', 2), ('Biology', 2), ('Evolution', 2), ('Atheism', 2), ('Anthologies', 2), ('Fairies', 2), ('Anthropology', 2), ('Holiday', 2), ('Dark Fantasy', 2), ('Metaphysics', 2), ('Slow Burn', 2), ('Astronomy', 2), ('Italian Literature', 2), ('Writing', 2), ('Halloween', 2), ('Found Family', 2), ('Yoga', 2), ('Family & Relationships', 2), ('Journalists', 2), ('Economists', 2), ('Iran', 2), ('Girls', 2), ('Slaves', 2), ('Religious Psychology', 2), ('Biography: general', 2), ('Entertainers', 2), ('Mathematicians', 2), ('Artists', 2), ('navy', 2), ('Literary collections', 2), ('collections', 2), ('Slavery', 2), ('Self-actualization (Psychology) in women', 2), ('Nationalists', 2), ('Computer programmers', 2), ('Married women', 2), ('Knowledge', 2), ('Theory of', 2), ('Youth', 2), ('Rich people', 2), ('Curricula', 2), ('Dictionaries', 2), ('Great britain', 2), ('Mothers', 2), ('memoir', 2), ('Psychopathology', 2), ('Revolutionaries', 2), ('english', 2), ('Educators', 2), ('Adventure and adventurers', 2), ('Children: Kindergarten', 2), ('True crime', 2), ('Serial Killer', 2), ('private investigators', 2), ('FBI', 2), ('Plants', 2), ('Parricide', 2), ('Christians', 2), ('Ficción', 2), ("Hell's Angels", 2), ('Motorcycle gangs', 2), ('California', 2), ('Aims and objectives', 2), ('Crime organisé', 2), ('Crime & mystery', 2), ('Identity (Psychology)', 2), ('Homicide', 2), ('Private investigators', 2), ('English Detective and mystery stories', 2), ('Criminal behavior', 2), ('Violent crimes', 2), ('Serial murder investigation', 2), ('political', 2), ('Cold War', 2), ('Discworld (Imaginary place)', 2), ('Yakuza', 2), ('Prisoners', 2), ('Missing persons', 2), ('Stock exchanges', 2), ('Bhagavadgītā', 2), ('Civilización', 2), ('Cults', 2), ('Liberté', 2), ('Technology and civilization', 2), ('Human beings', 2), ('National socialism', 2), ('Wereldgeschiedenis', 2), ('Architektur', 2), ('Modern Civilization', 2), ('Discovery and exploration', 2), ('1945-', 2), ('Intercultural communication', 2), ('Legends', 2), ('Feminist theory', 2), ('Judaism', 2), ('East and West', 2), ('Design', 2), ('Ethnology', 2), ('SOCIAL SCIENCE / Ethnic Studies / African American Studies', 2), ('Battle of', 2), ('Chemistry', 2), ('Poverty', 2), ('Juvenile Fiction', 2), ('Addresses', 2), ('Courtship', 2), ('Political ethics', 2), ('Religion and science', 2), ('Apologetics', 2), ('Self-control', 2), ('Psychology textbooks', 2), ('Life change events', 2), ('Egoism', 2), ('Character', 2), ('Aspectos psicológicos', 2), ('Specimens', 2), ('BODY', 2), ('Psychologie appliquée', 2), ('Procrastination', 2), ('Berrett Koehler', 2), ('social aspects', 2), ('Amor', 2), ('BUSINESS & ECONOMICS / General', 2), ('Consumption (Economics)', 2), ('Millionaires', 2), ('Marriage', 2), ('Self-deception', 2), ('Self-esteem', 2), ('Research', 2), ('mindfulness', 2), ('SELF-HELP / Personal Growth / Success', 2), ('Mothers and sons', 2), ('Self', 2), ('SELF-HELP / Motivational & Inspirational', 2), ('Holistic medicine', 2), ('Values', 2), ('Herbs', 2), ('Therapeutic use', 2), ('Romance fiction', 2), ('College students', 2), ('Survival', 2), ('Éxito', 2), ('self help', 2), ('Translations into Spanish', 2), ('Dinosaurs', 2), ('Philosophy and religion', 2), ('Voyages', 2), ('Travelers', 2), ('Automobile travel', 2), ('Love stories', 2), ('End of the world', 2), ('Literary Criticism', 2), ('Fathers and sons', 2), ('early works to 1800', 2), ('Didactic fiction', 2), ('Mice', 2), ('Extraterrestrial beings', 2), ('Frontier and pioneer life', 2), ('Arts', 2), ('Juvenile drama', 2), ('English Young adult drama', 2), ('Generals', 2), ('germany', 2), ('Imprisonment', 2), ('Political fiction', 2), ('Technological innovations', 2), ('The State', 2), ('Teaching', 2), ('historical fiction', 2), ('political fiction', 2), ('Radicalism', 2), ('Anarchism', 2), ('Cambodia', 2), ('Totalitarianism', 2), ('Constitutions', 2), ('Science politique', 2), ('Women gardeners', 2), ('Prime ministers', 2), ('Imperialism', 2), ('English fiction', 2), ('Antonius', 2), ('Bibliography', 2), ('Mulching', 2), ('Organic gardening', 2), ('Polarization (social science)', 2), ('Public opinion', 2), ('Critical pedagogy', 2), ('Translations into Italian', 2), ('Administrative law', 2), ('great britain', 2), ('Social policy', 2), ('Brothers and sisters', 2), ('International business enterprises', 2), ('Utilitarianism', 2), ('French essays', 2), ('Life', 2), ('Suicide', 2), ('Introductions', 2), ('Theory of Knowledge', 2), ('Color', 2), ('Mysticism', 2), ('Filosofie', 2), ('Logic', 2), ('Justice', 2), ('permaculture', 2), ('Language and languages', 2), ('Games', 2), ('Latin Didactic poetry', 2), ('Jurisprudence', 2), ('Love poetry', 2), ('Sociologie', 2), ('Stoics', 2), ('ancient', 2), ('Scottish', 2), ('Juvenile poetry', 2), ('Mathematics', 2), ('American Fantasy fiction', 2), ('Computers', 2), ('science', 2), ('Polish fiction', 2), ('Quests (Expeditions)', 2), ('Stories in rhyme', 2), ('OverDrive', 2), ('Criminology', 2), ('Officials and employees', 2), ('Crime And Criminals', 2), ('Stocks', 2), ('Cognition', 2), ('Murder victims', 2), ('study and teaching', 2), ('Psychological aspects of Economics', 2), ('Micro-economie', 2), ('Cases', 2), ('Consumer behavior', 2), ('Business & Economics', 2), ('Business / Economics / Finance', 2), ('economics', 2), ('Investments', 2), ('Classical school of economics', 2), ('International Competition', 2), ('technology', 2), ('Health aspects', 2), ('Longevity', 2), ('Health education', 2), ('Child psychology', 2), ('Child development', 2), ('Montessori method of education', 2), ('Child study', 2), ('Paranormal fiction', 2), ('General cookery', 2), ('Baking', 2), ('COOKING / Methods / Baking', 2), ('International Cookery', 2), ('Gastronomy', 2), ('Home economics', 2), ('Literary cookbooks', 2), ('European Literature', 1), ('Counting', 1), ('Autistic Spectrum Disorder', 1), ('Czech Literature', 1), ('Addiction', 1), ('Pirates', 1), ('Romantic Suspense', 1), ('Literary', 1), ('Portugal', 1), ('Werewolves', 1), ('Journalism', 1), ('College', 1), ('Egypt', 1), ('Nigeria', 1), ('Monsters', 1), ('Storytime', 1), ('18th Century', 1), ('Horror Thriller', 1), ('Metafiction', 1), ('Zombies', 1), ('Gay', 1), ('Medicine', 1), ('Ethiopia', 1), ('Middle East', 1), ('Romantic', 1), ('Young Adult Romance', 1), ('Meditation', 1), ('Social Justice', 1), ('Friends To Lovers', 1), ('Novella', 1), ('Psychological Thriller', 1), ('Murder Mystery', 1), ('Lds', 1), ('Church', 1), ('Art History', 1), ('Native American', 1), ('Indigenous', 1), ('World War I', 1), ('Wholesome', 1), ('Family Drama', 1), ('Animal Fiction', 1), ('Psychological', 1), ('Lesbian', 1), ('Smut', 1), ('Theory', 1), ('Academic', 1), ('Productivity', 1), ('Liberia', 1), ('Sierra Leone', 1), ('Christian Living', 1), ('Yogis', 1), ('Yoguis', 1), ('Entertainment & Performing Arts', 1), ('Biography & Autobiography / Personal Memoirs', 1), ('comedy', 1), ('Thompson', 1), ('hunter s.', 1), ('1937-2005', 1), ('biography & memoir', 1), ('Douglass', 1), ('frederick', 1), ('1818-1895', 1), ('African American abolitionists', 1), ('Abolitionists', 1), ('Psychoanalysis', 1), ('Psychology and religion', 1), ('Women poets', 1), ('Chelsea Hotel', 1), ('Women rock musicians', 1), ('Photographers', 1), ('Musicians', 1), ('apartheid', 1), ('PERFORMING ARTS', 1), ('HUMOR', 1), ('Television personalities', 1), ('Personal Memoirs', 1), ('Pimps', 1), ('Slums', 1), ('Cancer', 1), ('Lungs', 1), ('Husband and wife', 1), ('Veterinarians', 1), ('Herriot', 1), ('james', 1), ('1916-1995', 1), ('SpaceX (Firm)', 1), ('PayPal (Firm)', 1), ('Tesla Motors', 1), ('writing', 1), ('Salem’s Lot', 1), ('Happy Stamps', 1), ('The Elements of Style', 1), ('Portuguese Poets', 1), ('Poetas portugueses', 1), ("Rock musicians' spouses", 1), ('Popmuziek', 1), ('Biographie', 1), ('Cocineros', 1), ('Biography,', 1), ('Intellectual life', 1), ('Wiskundigen', 1), ('Gifted persons', 1), ('nyt:paperback-nonfiction=2018-10-21', 1), ('Biography/Autobiography', 1), ('nyt:combined-print-and-e-book-nonfiction=2023-11-12', 1), ('nyt:advice-how-to-and-miscellaneous=2019-01-13', 1), ('seals', 1), ('air force', 1), ('physics', 1), ('relativity', 1), ('scientific advancement', 1), ('quantum mechanics', 1), ('Friends and associates', 1), ("Children's rights", 1), ('English literature (collections)', 1), ('English literature.', 1), ('Psychotherapists', 1), ('Therapist and patient', 1), ('Psychotherapy BIOGRAPHY & AUTOBIOGRAPHY', 1), ('Actors', 1), ('Stripteasers', 1), ('Drogas alucinógenas', 1), ('Experiencias Religiosas', 1), ('Hallucinogenic drugs', 1), ('Hallucinogenic drugs and religious experience', 1), ('Sorcery', 1), ('Linux', 1), ('computer', 1), ('open source', 1), ('Special collections', 1), ('Cynthia Hilden', 1), ('Depressed persons', 1), ('Governors', 1), ('facetiae', 1), ('Baseball', 1), ('Baseball players', 1), ('Joueurs de base-ball', 1), ('Sex in literature', 1), ('Literature and morals', 1), ('in literature', 1), ('Sexo en literatura', 1), ('Literatura y moral', 1), ('Schizophrenics', 1), ('Schizofrenie', 1), ('Filosofen', 1), ('nyt:sports=2017-11-12', 1), ('Aptitudes empresariales', 1), ('Tennis players', 1), ('Sports & Rec

In [177]:
# running the MultiLabelBinarizer on genres column
mlb = MultiLabelBinarizer()
X_genres = mlb.fit_transform(books_model['genres_list'])
print('Genres shape:', X_genres.shape)

Genres shape: (2004, 2425)

Normalizing avg_rating, num_ratings, pages